### ISSUE TITLE
GdxExecutor do_swap 的滑点需要控制 

### ISSUE THREAD

**Issue by coolcode** [BlackMetamaskMan/gdx#1]
ty2.py line 135: 直接 swap GDX的会导致极大的滑点，估计是D5的GDX深度不足。解决办法：考虑聚合 uniswap ？

**Comment by BlackMetamaskMan** [comment]
嗯，聚合uniswap是个思路。另外可以做swap前判断池子的深度，然后再去swap。相当于加一个判定条件。
